apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image -}}:{{- .Values.tag }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 50m
              memory: 50Mi
          ports:
            - name: server
              containerPort: {{ .Values.serverPort }}
              protocol: TCP
          volumeMounts:
          env:
          envFrom:
      terminationGracePeriodSeconds: 15
      volumes:
